// DreamDiaryView.swift
// Agentics
//
// Displays the most recent entry from an agent's DREAMS.md file.
// DREAMS.md is generated by OpenClaw's Dreaming plugin (memory-core),
// which runs nightly and promotes strong conversation signals into MEMORY.md.
//
// The View button is disabled when DREAMS.md doesn't exist in the agent's
// workspace — meaning Dreaming hasn't been enabled or hasn't run yet.
//
// When the auto-install flow is built, this file is the right place to add
// any Dreaming-specific setup logic (plugin check, config write, etc).

import SwiftUI

struct DreamDiaryView: View {
    @Binding var agent: Agent
    @State private var showDreamDiary  = false
    @State private var dreamEntry:     String? = nil
    @State private var dreamTimestamp: String? = nil

    private var dreamsFilePath: String {
        let expanded = (agent.workspacePath as NSString).expandingTildeInPath
        return (expanded as NSString).appendingPathComponent("DREAMS.md")
    }

    private var dreamingEnabled: Bool {
        FileManager.default.fileExists(atPath: dreamsFilePath)
    }

    private func loadLatestEntry() {
        guard let raw = try? String(contentsOfFile: dreamsFilePath, encoding: .utf8),
              !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            dreamEntry     = nil
            dreamTimestamp = nil
            return
        }
        // Split on section headers, grab the last non-empty block
        let sections = raw.components(separatedBy: "\n## ")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        guard let last = sections.last else {
            dreamEntry     = nil
            dreamTimestamp = nil
            return
        }
        let lines      = last.components(separatedBy: "\n")
        dreamTimestamp = lines.first?.trimmingCharacters(in: .whitespacesAndNewlines)
        dreamEntry     = lines.dropFirst().joined(separator: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Label("Dreams", systemImage: "moon.stars.fill")
                .font(.system(size: 11, weight: .medium)).foregroundColor(Color.white.opacity(0.5))

            HStack {
                VStack(alignment: .leading, spacing: 2) {
                    Text("Dream Diary")
                        .font(.system(size: 13, weight: .medium)).foregroundColor(.white)
                    Text(dreamingEnabled ? "Available" : "Not configured")
                        .font(.system(size: 11))
                        .foregroundColor(dreamingEnabled ? Color.white.opacity(0.4) : Color.white.opacity(0.3))
                }
                Spacer()
                Button(action: {
                    loadLatestEntry()
                    showDreamDiary = true
                }) {
                    if dreamingEnabled {
                        Label("View", systemImage: "eye")
                            .font(.system(size: 11, weight: .medium))
                            .foregroundColor(Color(red: 1.0, green: 0.25, blue: 0.55))
                    } else {
                        Text("Dreaming not enabled")
                            .font(.system(size: 11, weight: .medium))
                            .foregroundColor(Color.white.opacity(0.25))
                    }
                }
                .buttonStyle(.plain)
                .disabled(!dreamingEnabled)
            }
            .padding(.horizontal, 10).padding(.vertical, 8)
            .glassBackground(opacity: 0.08, cornerRadius: 8, borderOpacity: 0.12)
        }
        .sheet(isPresented: $showDreamDiary) {
            DreamDiarySheet(
                agentName: agent.name,
                timestamp: dreamTimestamp,
                content:   dreamEntry
            )
        }
    }
}

struct DreamDiarySheet: View {
    let agentName: String
    let timestamp: String?
    let content:   String?
    @Environment(\.dismiss) var dismiss

    var body: some View {
        ZStack {
            Color(red: 0.12, green: 0.12, blue: 0.14).ignoresSafeArea()
            VStack(alignment: .leading, spacing: 0) {
                // Header
                HStack {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Dream Diary — \(agentName.capitalized)")
                            .font(.system(size: 15, weight: .semibold))
                            .foregroundColor(.white)
                        if let timestamp {
                            Text(timestamp)
                                .font(.system(size: 11))
                                .foregroundColor(Color.white.opacity(0.4))
                        }
                    }
                    Spacer()
                    Button(action: { dismiss() }) {
                        Image(systemName: "xmark.circle.fill")
                            .font(.system(size: 20))
                            .foregroundColor(Color.white.opacity(0.3))
                    }.buttonStyle(.plain)
                }
                .padding(.horizontal, 20)
                .padding(.top, 20)
                .padding(.bottom, 16)

                Divider().background(Color.white.opacity(0.08))

                ScrollView {
                    if let content, !content.isEmpty {
                        Text(content)
                            .font(.system(size: 13))
                            .foregroundColor(Color.white.opacity(0.8))
                            .lineSpacing(4)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(20)
                            .textSelection(.enabled)
                    } else {
                        Text("No dream entries yet.")
                            .font(.system(size: 13))
                            .foregroundColor(Color.white.opacity(0.4))
                            .frame(maxWidth: .infinity, alignment: .center)
                            .padding(.top, 40)
                    }
                }
            }
        }
        .frame(width: 520, height: 420)
    }
}
