// DreamDiaryView.swift
// Agentics
//
// Displays dream entries from an agent's DREAMS.md file, with optional
// DALL-E 3 generated imagery above each entry.
//
// DREAMS.md is generated by OpenClaw's Dreaming plugin (memory-core),
// which runs nightly and promotes strong conversation signals into MEMORY.md.
//
// The View button is disabled when DREAMS.md doesn't exist in the agent's
// workspace — meaning Dreaming hasn't been enabled or hasn't run yet.
//
// When the auto-install flow is built, this file is the right place to add
// any Dreaming-specific setup logic (plugin check, config write, etc).

import SwiftUI

// MARK: - Model

struct DreamEntry {
    let realDate:  String  // "2026-04-20" — used to match and save dream-YYYY-MM-DD.png
    let timestamp: String  // Display timestamp (time randomised ±90 min from 3:00 AM)
    let content:   String
}

// MARK: - Settings panel row

struct DreamDiaryView: View {
    @Binding var agent: Agent
    @State private var showDreamDiary         = false
    @State private var dreamEntries: [DreamEntry] = []
    @State private var imageGenerationEnabled: Bool

    init(agent: Binding<Agent>) {
        _agent = agent
        _imageGenerationEnabled = State(initialValue: UserDefaults.standard.bool(
            forKey: "dreamImagesEnabled-\(agent.wrappedValue.id)"
        ))
    }

    private var dreamsFilePath: String {
        let expanded = (agent.workspacePath as NSString).expandingTildeInPath
        return (expanded as NSString).appendingPathComponent("DREAMS.md")
    }

    private var dreamingEnabled: Bool {
        FileManager.default.fileExists(atPath: dreamsFilePath)
    }

    // MARK: - Parsing

    // Parses DREAMS.md and returns the 5 most recent entries, newest first.
    //
    // Format written by memory-core:
    //   <!-- openclaw:dreaming:diary:start -->
    //   ---
    //   *April 20, 2026 at 3:00 AM CDT*
    //   <content>
    //   ---
    //   <!-- openclaw:dreaming:diary:end -->
    //
    // Splitting on "\n---\n" gives one block per entry. The first single-line
    // *...* in each block is the timestamp; everything after is content.
    private func loadEntries() {
        guard let raw = try? String(contentsOfFile: dreamsFilePath, encoding: .utf8),
              !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            dreamEntries = []
            return
        }

        let startMarker = "<!-- openclaw:dreaming:diary:start -->"
        let endMarker   = "<!-- openclaw:dreaming:diary:end -->"
        var body = raw
        if let s = raw.range(of: startMarker), let e = raw.range(of: endMarker) {
            body = String(raw[s.upperBound..<e.lowerBound])
        }

        let blocks = body
            .components(separatedBy: "\n---\n")
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }

        let parsed: [DreamEntry] = blocks.compactMap { block in
            let lines = block.components(separatedBy: "\n")
            guard let tsIdx = lines.firstIndex(where: {
                $0.hasPrefix("*") && $0.hasSuffix("*") && !$0.dropFirst().dropLast().contains("\n")
            }) else { return nil }

            let rawTimestamp = lines[tsIdx]
                .trimmingCharacters(in: CharacterSet(charactersIn: "*").union(.whitespaces))
            let realDate  = extractRealDate(from: rawTimestamp)
            let timestamp = randomizedTimestamp(rawTimestamp)
            let content   = lines[(tsIdx + 1)...]
                .joined(separator: "\n")
                .trimmingCharacters(in: .whitespacesAndNewlines)

            return DreamEntry(realDate: realDate, timestamp: timestamp, content: content)
        }

        // Newest first, capped at 5
        dreamEntries = Array(parsed.reversed().prefix(5))
    }

    // Extracts "2026-04-20" from "April 20, 2026 at 3:00 AM CDT"
    private func extractRealDate(from timestamp: String) -> String {
        let inputFmt        = DateFormatter()
        inputFmt.locale     = Locale(identifier: "en_US_POSIX")
        inputFmt.dateFormat = "MMMM d, yyyy"

        let outputFmt        = DateFormatter()
        outputFmt.dateFormat = "yyyy-MM-dd"

        guard let atRange = timestamp.range(of: " at ") else { return timestamp }
        let datePart = String(timestamp[..<atRange.lowerBound])
        if let date = inputFmt.date(from: datePart) {
            return outputFmt.string(from: date)
        }
        return datePart
    }

    // Replaces the real time with a ±90-min offset seeded by the timestamp string,
    // so the same entry always shows the same fake time — feels organic, not mechanical.
    private func randomizedTimestamp(_ timestamp: String) -> String {
        let seed  = UInt64(bitPattern: Int64(timestamp.hashValue))
        let lcg   = 6364136223846793005 &* seed &+ 1442695040888963407
        let offsetMinutes = Int(lcg % 181) - 90

        let totalMinutes = max(0, min(1439, 180 + offsetMinutes))
        let hour24  = totalMinutes / 60
        let minute  = totalMinutes % 60
        let hour12  = hour24 == 0 ? 12 : (hour24 > 12 ? hour24 - 12 : hour24)
        let ampm    = hour24 < 12 ? "AM" : "PM"
        let newTime = String(format: "%d:%02d %@", hour12, minute, ampm)

        guard let atRange = timestamp.range(of: " at ") else { return timestamp }
        let datePart  = String(timestamp[..<atRange.upperBound])
        let remainder = String(timestamp[atRange.upperBound...])
        let parts     = remainder.components(separatedBy: " ")
        let tz        = parts.count >= 3 ? " \(parts[parts.count - 1])" : ""
        return "\(datePart)\(newTime)\(tz)"
    }

    // MARK: - View

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Label("Dreams", systemImage: "moon.stars.fill")
                .font(.system(size: 11, weight: .medium))
                .foregroundColor(Color.white.opacity(0.5))

            VStack(spacing: 0) {

                // Main row — title + View button
                HStack {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Dream Diary")
                            .font(.system(size: 13, weight: .medium))
                            .foregroundColor(.white)
                        Text(dreamingEnabled ? "Available" : "Not configured")
                            .font(.system(size: 11))
                            .foregroundColor(dreamingEnabled
                                ? Color.white.opacity(0.4)
                                : Color.white.opacity(0.3))
                    }
                    Spacer()
                    Button {
                        loadEntries()
                        showDreamDiary = true
                    } label: {
                        if dreamingEnabled {
                            Label("View", systemImage: "eye")
                                .font(.system(size: 11, weight: .medium))
                                .foregroundColor(Color(red: 1.0, green: 0.25, blue: 0.55))
                        } else {
                            Text("Dreaming not enabled")
                                .font(.system(size: 11, weight: .medium))
                                .foregroundColor(Color.white.opacity(0.25))
                        }
                    }
                    .buttonStyle(.plain)
                    .disabled(!dreamingEnabled)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 8)

                // Image generation toggle — only shown when dreaming is active
                if dreamingEnabled {
                    Divider().background(Color.white.opacity(0.06))
                    HStack {
                        Image(systemName: "photo.artframe")
                            .font(.system(size: 11))
                            .foregroundColor(Color.white.opacity(0.4))
                        Text("Generate dream images")
                            .font(.system(size: 12))
                            .foregroundColor(Color.white.opacity(0.6))
                        Spacer()
                        Toggle("", isOn: $imageGenerationEnabled)
                            .toggleStyle(.switch)
                            .tint(Color(red: 1.0, green: 0.25, blue: 0.55))
                            .scaleEffect(0.75)
                            .frame(width: 40)
                            .onChange(of: imageGenerationEnabled) { _, newValue in
                                UserDefaults.standard.set(
                                    newValue,
                                    forKey: "dreamImagesEnabled-\(agent.id)"
                                )
                            }
                    }
                    .padding(.horizontal, 10)
                    .padding(.vertical, 7)
                }
            }
            .glassBackground(opacity: 0.08, cornerRadius: 8, borderOpacity: 0.12)
        }
        .sheet(isPresented: $showDreamDiary) {
            DreamDiarySheet(
                agentName:              agent.name,
                entries:                dreamEntries,
                workspace:              agent.workspacePath,
                agentId:                agent.id,
                imageGenerationEnabled: $imageGenerationEnabled
            )
        }
    }
}

// MARK: - Sheet

struct DreamDiarySheet: View {
    let agentName: String
    let entries:   [DreamEntry]
    let workspace: String
    let agentId:   String
    @Binding var imageGenerationEnabled: Bool

    @ObservedObject private var imageService = DreamImageService.shared
    @Environment(\.dismiss) var dismiss

    var body: some View {
        ZStack {
            Color(red: 0.12, green: 0.12, blue: 0.14).ignoresSafeArea()

            VStack(alignment: .leading, spacing: 0) {

                // Header
                HStack {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Dream Diary — \(agentName.capitalized)")
                            .font(.system(size: 15, weight: .semibold))
                            .foregroundColor(.white)
                        Text("\(entries.count) \(entries.count == 1 ? "entry" : "entries")")
                            .font(.system(size: 11))
                            .foregroundColor(Color.white.opacity(0.4))
                    }
                    Spacer()

                    Button { dismiss() } label: {
                        Image(systemName: "xmark.circle.fill")
                            .font(.system(size: 20))
                            .foregroundColor(Color.white.opacity(0.3))
                    }
                    .buttonStyle(.plain)
                    .padding(.leading, 10)
                }
                .padding(.horizontal, 20)
                .padding(.top, 20)
                .padding(.bottom, 16)

                Divider().background(Color.white.opacity(0.08))

                // Image generation toggle row
                HStack {
                    Image(systemName: "photo.artframe")
                        .font(.system(size: 11))
                        .foregroundColor(Color.white.opacity(0.4))
                    Text("Dream images")
                        .font(.system(size: 12))
                        .foregroundColor(.white)
                    Spacer()
                    Toggle("", isOn: $imageGenerationEnabled)
                        .toggleStyle(.switch)
                        .tint(Color(red: 1.0, green: 0.25, blue: 0.55))
                        .scaleEffect(0.75)
                        .frame(width: 40)
                        .onChange(of: imageGenerationEnabled) { _, newValue in
                            UserDefaults.standard.set(
                                newValue,
                                forKey: "dreamImagesEnabled-\(agentId)"
                            )
                        }
                }
                .padding(.horizontal, 20)
                .padding(.vertical, 8)

                Divider().background(Color.white.opacity(0.08))

                // Entries
                ScrollView {
                    if entries.isEmpty {
                        Text("No dream entries yet.")
                            .font(.system(size: 13))
                            .foregroundColor(Color.white.opacity(0.4))
                            .frame(maxWidth: .infinity, alignment: .center)
                            .padding(.top, 40)
                    } else {
                        LazyVStack(alignment: .leading, spacing: 0) {
                            ForEach(Array(entries.enumerated()), id: \.offset) { index, entry in
                                VStack(alignment: .leading, spacing: 12) {

                                    // Dream image (or loading placeholder)
                                    dreamImageView(for: entry)

                                    // Timestamp
                                    Text(entry.timestamp)
                                        .font(.system(size: 15, weight: .semibold))
                                        .foregroundColor(
                                            Color(red: 1.0, green: 0.25, blue: 0.55).opacity(0.8)
                                        )

                                    // Content
                                    Text(entry.content)
                                        .font(.system(size: 13))
                                        .foregroundColor(Color.white.opacity(0.8))
                                        .lineSpacing(4)
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                        .textSelection(.enabled)
                                }
                                .padding(20)

                                if index < entries.count - 1 {
                                    Divider().background(Color.white.opacity(0.08))
                                }
                            }
                        }
                    }
                }
            }
        }
        .frame(width: 540, height: 560)
        // Generate missing images when sheet opens
        .task {
            await generateIfEnabled()
        }
        // Generate if toggle is turned on while sheet is open
        .onChange(of: imageGenerationEnabled) { _, enabled in
            if enabled {
                Task { await generateIfEnabled() }
            }
        }
    }

    // MARK: - Image view

    @ViewBuilder
    private func dreamImageView(for entry: DreamEntry) -> some View {
        if let path = imageService.imagePath(for: entry, workspace: workspace),
           let nsImage = NSImage(contentsOfFile: path) {
            Image(nsImage: nsImage)
                .resizable()
                .aspectRatio(contentMode: .fill)
                .frame(maxWidth: .infinity)
                .frame(height: 180)
                .clipped()
                .clipShape(RoundedRectangle(cornerRadius: 10))
        } else if imageGenerationEnabled && imageService.generatingFor.contains(entry.realDate) {
            RoundedRectangle(cornerRadius: 10)
                .fill(Color.white.opacity(0.04))
                .frame(maxWidth: .infinity)
                .frame(height: 60)
                .overlay {
                    HStack(spacing: 8) {
                        ProgressView()
                            .scaleEffect(0.7)
                            .tint(Color.white.opacity(0.4))
                        Text("Generating dream image...")
                            .font(.system(size: 11))
                            .foregroundColor(Color.white.opacity(0.3))
                    }
                }
        }
    }

    // MARK: - Generation

    private func generateIfEnabled() async {
        guard imageGenerationEnabled else { return }
        await imageService.generateMissing(
            entries: entries,
            workspace: workspace,
            agentId: agentId
        )
    }
}
